apiVersion: apps/v1
kind: Deployment
metadata:
  name: caseclinical-underwriting-service
  namespace: pch
  labels:
    app: caseclinical-underwriting-service
    tags.datadoghq.com/env: Production
    tags.datadoghq.com/service: caseclinical-underwriting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caseclinical-underwriting-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        admission.datadoghq.com/js-lib.version: latest
      name: caseclinical-underwriting-service
      labels:
        app: caseclinical-underwriting-service
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: Production
        tags.datadoghq.com/service: caseclinical-underwriting-service
    spec:
      initContainers:
        - name: migration
          image: caseclinical.azurecr.io/caseclinical-underwriting-migration
          imagePullPolicy: IfNotPresent
          env:
            #### SECRETS ####
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: underwriting-secrets
                  key: DATABASE_URL
      containers:
      - name: caseclinical-underwriting-service
        image: caseclinical.azurecr.io/caseclinical-underwriting-service
        imagePullPolicy: IfNotPresent
        env:
        ##### CONFIGS #####
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_STARTUP_LOGS
          value: "true"
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: underwriting-configs
              key: AZURE_STORAGE_ACCOUNT_NAME
        - name: AZURE_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: underwriting-configs
              key: AZURE_STORAGE_ACCOUNT_CONTAINER_NAME
        - name: MATRIX_CHAT_URL
          valueFrom:
            configMapKeyRef:
              name: underwriting-configs
              key: MATRIX_CHAT_URL
        - name: WEB_URL
          valueFrom:
            configMapKeyRef:
              name: underwriting-configs
              key: WEB_URL
        - name: WSS_URL
          valueFrom:
            configMapKeyRef:
              name: underwriting-configs
              key: WSS_URL
        ##### SECRETS #####
        - name: AZURE_STORAGE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: underwriting-secrets
              key: AZURE_STORAGE_ACCOUNT_CONNECTION_STRING
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: underwriting-secrets
              key: AZURE_STORAGE_ACCOUNT_KEY
        - name: AZURE_STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: underwriting-secrets
              key: AZURE_STORAGE_ACCOUNT_URL
        - name: AZURE_STORAGE_SAS_KEY
          valueFrom:
            secretKeyRef:
              name: underwriting-secrets
              key: AZURE_STORAGE_ACCOUNT_SAS_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: underwriting-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: underwriting-secrets
              key: JWT_SECRET
        resources:
          requests:
            cpu: 50m
            memory: 350Mi 
          limits:
            cpu: 250m
            memory: 700Mi
        ports:
        - containerPort: 3000