apiVersion: apps/v1
kind: Deployment
metadata:
  name: caseclinical-underwriting-frontend
  namespace: pch
  labels:
    app: caseclinical-underwriting-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caseclinical-underwriting-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: caseclinical-underwriting-frontend
      labels:
        app: caseclinical-underwriting-frontend
    spec:
      containers:
      - name: caseclinical-underwriting-frontend
        image: caseclinicaluat.azurecr.io/caseclinical-underwriting-frontend
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 150Mi 
          limits:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 80