BEGIN TRY

BEGIN TRAN;

-- AddForeignKey
ALTER TABLE [dbo].[ClaimProcedure] ADD CONSTRAINT [ClaimProcedure_procedureCodeId_fkey] FOREIGN KEY ([procedureCodeId]) REFERENCES [dbo].[Procedure]([id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
