FROM node:16-alpine3.15 as build-step
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn install
RUN yarn global add @nrwl/cli
ENV NODE_OPTIONS=--max-old-space-size=16000
COPY . .
RUN yarn build:web

# nginx by default export port 80 and we don't need to expose another port
FROM nginx:1.17.1-alpine
COPY --from=build-step /app/dist/apps/web /usr/share/nginx/html
