
export * from './lib/dto/admin-create-medical-record.input'
export * from './lib/dto/admin-list-medical-record.input'
export * from './lib/dto/admin-update-medical-record.input'
export * from './lib/dto/medical-record.input'
export * from './lib/dto/user-create-medical-record.input'
export * from './lib/dto/user-list-medical-record.input'
export * from './lib/dto/user-update-medical-record.input'
export * from './lib/dto/user-update-medical-records.input'
export * from './lib/models/medical-record.model'
export * from './lib/api-medical-record-data-access.module'

export * from './lib/api-medical-record-data-access-admin.service'
export * from './lib/api-medical-record-data-access-public.service'
export * from './lib/api-medical-record-data-access-user.service'
