
export * from './lib/dto/admin-create-gender.input'
export * from './lib/dto/admin-list-gender.input'
export * from './lib/dto/admin-update-gender.input'
export * from './lib/dto/gender.input'
export * from './lib/dto/user-create-gender.input'
export * from './lib/dto/user-list-gender.input'
export * from './lib/dto/user-update-gender.input'
export * from './lib/dto/user-update-genders.input'
export * from './lib/models/gender.model'
export * from './lib/api-gender-data-access.module'

export * from './lib/api-gender-data-access-admin.service'
export * from './lib/api-gender-data-access-public.service'
export * from './lib/api-gender-data-access-user.service'
