FROM node:18.13.0-alpine

COPY api-package.json package.json
RUN yarn

ENV NODE_OPTIONS=--max-old-space-size=16000
COPY . .
COPY api-package.json package.json

CMD ["yarn", "prisma", "migrate", "deploy"]