FROM node:16-alpine3.15 as build-step
WORKDIR /app
COPY package.json .
COPY yarn.lock .

RUN yarn install
RUN yarn global add @nrwl/cli
ENV NODE_OPTIONS=--max-old-space-size=16000
COPY . .
RUN yarn prisma:generate
RUN yarn build:web

FROM nginx:1.20-alpine
COPY --from=build-step /app/dist/apps/web /usr/share/nginx/html
COPY /nginx-custom.conf /etc/nginx/conf.d/default.conf
