export const selectFormVariants = [

  'academy-category',
  'accident-type',
  'account-status',
  'adverse-insurance-status',
  'agreement-type',
  'appointment-status',
  'appointment',
  'attorney-status',
  'attorney-type',
  'attorney',
  'authorization',
  'authorization-category',
  'authorization-kind',
  'authorization-status',
  'authorization-type',
  'balance-request',
  'bank',
  'batch-control',
  'body-part-lead',
  'body-part',
  'calculation-basis-type',
  'case-account-payment',
  'case-account',
  'case-pre-accident',
  'case-pre-injury',
  'case-pre-problem',
  'case-pre-procedure',
  'case-procedure',
  'case-progress-status',
  'case-status',
  'case-type',
  'category',
  'claim',
  'claim-procedure',
  'claim-status',
  'clinical-provider',
  'clinical-provider-location-availability',
  'clinical-provider-location',
  'clinical-provider-specialty',
  'clinical-provider-tag',
  'contact-email',
  'contact-kind',
  'contact-phone-number',
  'contact-setting',
  'contact-tag',
  'contact',
  'contract-kind',
  'contract-term',
  'contract',
  'contracted-rate-kind',
  'contracted-rate',
  'cost-category',
  'country',
  'diagnosis-code',
  'document-type',
  'durable-medical-equipment',
  'equipment',
  'ethnicity',
  'facility-fee-schedule',
  'favorite-provider',
  'fee-schedule',
  'firm-status',
  'firm',
  'gender',
  'guideline-used',
  'guideline',
  'health-insurance',
  'implant-category',
  'implant',
  'insurance-sector',
  'insurance-type',
  'insurance',
  'integration',
  'invoice-detail',
  'invoice',
  'journal-entry',
  'language',
  'lead-action',
  'lead-source',
  'lead-status',
  'lead',
  'legal-case',
  'location',
  'manufacturer',
  'med-level',
  'medical-condition-provider',
  'medical-condition',
  'medical-record-status',
  'medical-record',
  'motor-vehicle-accident',
  'organization',
  'patient-study',
  'patient-treatment-status',
  'patient',
  'payment-application-method',
  'payment-type',
  'payment',
  'payor-type',
  'pch-provider',
  'place-of-service',
  'portfolio',
  'prescription',
  'prior-auth-dme',
  'prior-auth-guideline',
  'prior-authorization-diagnosis-code',
  'prior-authorization-equipment',
  'prior-authorization-implant',
  'prior-authorization-procedure-code',
  'prior-authorization-request',
  'prior-meds-to-date-status',
  'prior-meds-to-date',
  'procedure-site',
  'procedure-status',
  'procedure-statuses',
  'procedure-type',
  'procedure-vendor-status',
  'procedure-vendor-statuses',
  'procedure-vendor',
  'procedure',
  'process',
  'recommended-order-authorizations',
  'recommended-order-diagnosis-codes',
  'recommended-orders',
  'reconciliation-period-type',
  'referral-requests',
  'request-additional-visits',
  'required-field',
  'review',
  'role',
  'service',
  'setting',
  'severity',
  'specialty',
  'specialty',
  'surgical-position',
  'surgical-position',
  'tag',
  'task-item',
  'task-tag',
  'team-role',
  'team-user',
  'team',
  'template',
  'underwriting',
  'user-course-progress',
  'user-role',
  'user',
  'vendor-location',
  'vendor-type',
  'vendor',
  'visit-kind',
  'write-off-status',
  'write-off',
  // 'accident-information',
  // 'document',
  // 'feature-permission',
  // 'feature',
  // 'message',
  // 'motor-vehicle-accident',
  // 'navigation',
  // 'notification',
  // 'permission',
  // 'role-permission',
  // 'shortcut',
  // 'team-role',
  // 'team-user',
  // 'team',
  // 'underwriting',
  // 'user-feature-permission',
  // 'user-feature',
  //'assigned-document',
  //'chat',
  //'course',
  //'premise-accident',
  //'product-liability',
  //'provider-location',
  //'role-permission',
  //'work-related',
]
