export const webFormVariants = [
    'lead',
    'lead-action',
    'lead-status',
    'lead-source',
  //   'body-part-lead',
  //   'body-part',
  //   'severity',
  //   'academy-category',
  //   'accident-information',
  //   'accident-type',
  //   'account-status',
  //   'adverse-insurance-status',
  //   'agreement-type',
  //   'appointment',
  //   'appointment-status',
  //   'assigned-document',
  //   'attorney',
  //   'attorney-status',
  //   'attorney-type',
  //   'authorization-kind',
  //   'authorization-status',
  //   'bank',
  //   'balance-request',
  //   'batch-control',
  //   'calculation-basis-type',
  //   'case-account',
  //   'case-account-payment',
  //   'case-pre-accident',
  //   'case-pre-injury',
  //   'case-pre-problem',
  //   'case-pre-procedure',
  //   'case-procedure',
  //   'case-progress-status',
  //   'case-status',
  //   'case-type',
  //   'category',
  //   //'chat',
  //   'claim',
  //   'claim-procedure',
  //   'claim-status',
  //   'clinical-provider',
  //   'clinical-provider-location',
  //   'clinical-provider-location-availability',
  //   'clinical-provider-specialty',
  //   'clinical-provider-tag',
  //   'contact',
  //   'contact-email',
  //   'contact-kind',
  //  'contact-phone-number',
  //   'contact-setting',
  //   'contact-tag',
  //   'contract',
  //   'contracted-rate',
  //   'contracted-rate-kind',
  //   'contract-kind',
  //   'contract-term',
  //   'cost-category',
  //   'country',
  //   'course',
  //   'diagnosis-code',
  //   'document',
  //   'document-type',
  //   'durable-medical-equipment',
  //   'equipment',
  //   'ethnicity',
  //   'facility-fee-schedule',
  //   'favorite-provider',
  //   // 'feature',
  //   'feature-permission',
  //   'fee-schedule',
  //   'firm',
  //   'firm-status',
  //   'gender',
  //   'guideline',
  //   'guideline-used',
  //   'health-insurance',
  //   'implant',
  //    'implant-category',
  //   'insurance',
  //   'insurance-sector',
  //   'insurance-type',
  //   'integration',
  //   'journal-entry',
  //   'language',
  //   'legal-case',
  //   'location',
  //   'manufacturer',
  //   'medical-condition',
  //   'medical-condition-provider',
  //   'medical-record',
  //   'med-level',
  //   'message',
  //   'motor-vehicle-accident',
  //   'navigation',
  //   'notification',
  //   'motor-vehicle-accident',
  //   'organization',
  //   'patient',
  //   'patient-study',
  //   'patient-treatment-status',
  //   'payment',
  //   'payment-application-method',
  //   'payment-type',
  //   'payor-type',
  //   'permission',
  //   'pch-provider',
  //   'place-of-service',
  //   'portfolio',
  //   'premise-accident',
  //   'prescription',
  //   'prior-auth-dme',
  //   'prior-auth-guideline',
  //   'prior-authorization-diagnosis-code',
  //   'prior-authorization-equipment',
  //   'prior-authorization-implant',
  //   'prior-authorization-procedure-code',
  //   'prior-authorization-request',
  //   'prior-meds-to-date',
  //   'prior-meds-to-date-status',
  //   'procedure',
  //   'procedure-site',
  //   'procedure-type',
  //   'procedure-vendor',
  //   'process',
  //   'product-liability',
  //   'reconciliation-period-type',
  //   'required-field',
  //   'review',
  //   'role',
  //   //'role-permission',
  //   // 'role-permission',
  //   'setting',
  //   // 'shortcut',
  // 'specialty',
  // 'surgical-position',
  // // 'team',
  // // 'team-role',
  // // 'team-user',
  // // 'template',
  // // 'underwriting',
  // 'user',
  // 'user-course-progress',
  // // 'user-feature',
  // // 'user-feature-permission',
  //   'specialty',
  //   'surgical-position',
  //   'tag',
  //   'team',
  //   'team-role',
  //   'team-user',
  //   'underwriting',
  //   'user-role',
  //   'vendor',
  //   'vendor-type',
  //   'visit-kind',
  //   //'work-related',
  //   'write-off',
  //   'write-off-status'
  ]
